services:
  - type: web
    name: telegram-bot-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app --bind 0.0.0.0:$PORT
    envVars:
      - key: BOT_TOKEN
        fromSecret: true

  - type: worker
    name: telegram-bot-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: true